language: python

branches:
  only:
    - master

before_install:
  - git clone https://github.com/kward/shunit2.git /tmp/shunit2
  - git clone https://github.com/heroku/heroku-buildpack-testrunner.git /tmp/testrunner

install: true

script: sudo -E /tmp/testrunner/bin/run -c .

env:
  global:
    - SHUNIT_HOME="/tmp/shunit2/source/2.1"
